<?php /*Generated by WE 8.1.5.0, REV 12506, 2021-05-20, 17:10*/
$GLOBALS['WE_IS_DYN'] = 1;
$GLOBALS['we_transaction'] = 0;
$GLOBALS['we_ContentType'] = 'text/webedition';
$_REQUEST['we_cmd'] = [1 => 206];

if(empty($GLOBALS['we']['main']) && isset($_REQUEST['we_objectID'])) {
	require($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/we_showObject.inc.php');
} else {
	require($_SERVER['DOCUMENT_ROOT'] .  '/webEdition/we/include/we_showDocument.inc.php');
}